let tshirt = [
    {
        id: 1,
        name: "오렌지 티셔츠",
        desc: "오렌지 그림이 있는 티셔츠입니다.",
        price: 20000,
        stock: 10,
        gender: "woman",
        src: "assets/img/t1.webp",
    },
    {
        id: 2,
        name: "야자수 티셔츠",
        desc: "야자수 그림이 있는 티셔츠입니다.",
        price: 15000,
        stock: 10,
        gender: "man",
        src: "assets/img/t2.webp",
    },
    {
        id: 3,
        name: "yes 티셔츠",
        desc: "yes 그림이 있는 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "man",
        src: "assets/img/t3.webp",
    },
    {
        id: 4,
        name: "Not Today 티셔츠",
        desc: "Not Today 그림이 있는 티셔츠입니다.",
        price: 12000,
        stock: 20,
        gender: "man",
        src: "assets/img/t4.webp",
    },
    {
        id: 5,
        name: "Heart 티셔츠",
        desc: "심장 그림이 있는 살구색 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "man",
        src: "assets/img/t5.webp",
    },
    {
        id: 6,
        name: "파란색 티셔츠",
        desc: "글이 써 있는 파란색의 티셔츠입니다.",
        price: 15000,
        stock: 20,
        gender: "woman",
        src: "assets/img/t6.webp",
    },
    {
        id: 7,
        name: "그라데이션 티셔츠",
        desc: "그라데이션이 있는 티셔츠입니다.",
        price: 12000,
        stock: 10,
        gender: "woman",
        src: "assets/img/t7.webp",
    },
    {
        id: 8,
        name: "smile 티셔츠",
        desc: "smile 그림이 있는 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "woman",
        src: "assets/img/t8.webp",
    },
    {
        id: 9,
        name: "oops 티셔츠",
        desc: "oops 그림이 있는 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "man",
        src: "assets/img/t9.webp",
    },
    {
        id: 10,
        name: "치타 티셔츠",
        desc: "치타 그림이 있는 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "woman",
        src: "assets/img/t10.webp",
    },
    {
        id: 11,
        name: "손모양 티셔츠",
        desc: "손 그림이 있는 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "man",
        src: "assets/img/t11.webp",
    },
    {
        id: 12,
        name: "weird 티셔츠",
        desc: "weird 그림이 있는 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "woman",
        src: "assets/img/t12.webp",
    },
    {
        id: 13,
        name: "하늘색 자전거 그림 티셔츠",
        desc: "자전거가 그려져있는 하늘색의 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "man",
        src: "assets/img/t13.webp",
    },
    {
        id: 14,
        name: "연노랑 티셔츠",
        desc: "연노랑색의 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "woman",
        src: "assets/img/t14.webp",
    },
    {
        id: 15,
        name: "분홍색 티셔츠",
        desc: "꽃 그림이 있는 분홍색의 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "woman",
        src: "assets/img/t15.webp",
    },
    {
        id: 16,
        name: "아토믹 회색 티셔츠",
        desc: "원자 그림이 있는 티셔츠입니다.",
        price: 10000,
        stock: 20,
        gender: "man",
        src: "assets/img/t16.webp",
    },
];

export default tshirt;